### ISSUE TITLE
Command fillmegamap incorrectly overrides

### ISSUE THREAD

**Issue by naqaden** [Stormwind99/MegaMap#1]
To be clear, I haven't experienced any problem myself, but I use the [HelpFixer](https://minecraft.curseforge.com/projects/helpfixer/) mod and it's reporting the following 4x in a row each startup:
`[Server thread/WARN] [com.matthewprenger.helpfixer.HelpFixer]: Command fillmegamap incorrectly overrides compareTo: %s`

**Comment by Stormwind99** [comment]
Thanks!  I wonder what is incorrect about it...

**Comment by naqaden** [comment]
[This](https://github.com/matthewprenger/HelpFixer/blob/master/src/main/java/com/matthewprenger/helpfixer/HelpFixer.java#L71), which does [this](https://github.com/matthewprenger/HelpFixer/blob/master/src/main/java/com/matthewprenger/helpfixer/HelpFixer.java#L86).

**Comment by Stormwind99** [comment]
Ah, looks like ICommands need to implement a proper IComparable<>.compareTo().

Easiest way appears to be to replace implementing ICommand with extending net.minecraft.command.CommandBase.

Fixed in next release.   Thanks!

**Comment by naqaden** [comment]
Nice, thank you.
